---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1gpy47x9eernqydx2yrm96jn37tyachnfvm3celr70yw3jlddt3fs8emu9x"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1gpy47x9eernqydx2yrm96jn37tyachnfvm3celr70yw3jlddt3fs8emu9x"
