apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:RrSpvmW1Nan/jbAHJ1nTMabnOGWuBhhc7cae2t/Q+j3QuK8J,iv:50vKl6d50UjY3+rL1Cn/CETEdT2x1eCQe2CFfsxv8SA=,tag:PYdGzz6GtmUXo+YxMGg+Lw==,type:str]
    credentials.json: ENC[AES256_GCM,data:0zRyzpFH1IPhWLG/R2PAzi1dvLRaAHoX1Ahhqk0BmJGdd581i0o2JM+59QRsU4fjTSBmWsEF/S1ZBWfmyxlBHOO1/fnRdIyz7mBCjO/75LmKtJFjUuXPn64ofSI1fWrKQo19o9AhDO8ZRqnS0H8rFNALqySqo1SLEwNUcq885e4AAE9GLfugmqyVflVn5QveAV7cWhVBfgxy0w+2KcySKedjEpGfYLrD20w4tx6DZw==,iv:wi3ZCyvls0qdiUeoDcrTHwvD+ZXKbF+5CS5ebOO5jTg=,tag:PVxDBd6vWiXZ8KjNt4Hf6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gpy47x9eernqydx2yrm96jn37tyachnfvm3celr70yw3jlddt3fs8emu9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYXJ1eGk0NkdHdllXMmhL
            bkhmajRKRnROb1FKTUlwOHYvZGRVOTZYcHpzCk5DS3M0dDB2RjNBSTZwOXhXYkVU
            OVdKcnd6eFFONlovMzJ3bnErcjlsWk0KLS0tIDVxakxYZy9tRjhpT0FYa3RFbzl4
            dGNQZlVDOWs4U01yRmNneFZkaFkxa2cKOHHpxEbZCGaZGZkQETzGl1TTvt01R4jc
            QdUSLW0ZGuoxQPLRKUI2wJCXEWMy9RwRpgiweBpiUiUNYypQeJnK/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T20:13:05Z"
    mac: ENC[AES256_GCM,data:QcJF4mgEk1QOeqj2S+gKVMSqUeqF9BviV25vTQrkze4639SNOWO0tC5ClztDSQ+qFmD9xngFWCaJaqd+wdTkJw0YJLjUzggmfpAC94uuqTO0zZJN5n6+L6TjAB86vwl2Kjem6iopg8PU7KgBYa6JwTcaeYQc/0bilodcu/QN4mE=,iv:DWyV/XCOlsnbf2/NHV1Z1ZX59/B8gTjaeS49o9LSAl0=,tag:7LSV7dS3mirhQ9S+0LVWLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
